Traceback (most recent call last):
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\jmmau\anaconda3\envs\workenv\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig0, axes = plt.subplots(nrows=2, ncols=1, figsize=(6, 6),sharex=True)

axes[0].plot(pr.T,pr.get_values('V_POI'),label='$V_{POI}$')
axes[1].plot(pr.T,pr.get_values('Q_PMV')/1e6,label='$Q_{PMV}$')
axes[0].set_ylabel('Voltage (p.u.)')
axes[1].set_ylabel('Reactive Power (Mvar)')
axes[1].set_xlabel('Time (s)')

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mUnboundLocalError[0m                         Traceback (most recent call last)
[1;32m<ipython-input-9-794757c5a77b>[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [0maxes[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m.[0m[0mplot[0m[1;33m([0m[0mpr[0m[1;33m.[0m[0mT[0m[1;33m,[0m[0mpr[0m[1;33m.[0m[0mget_values[0m[1;33m([0m[1;34m'V_POI'[0m[1;33m)[0m[1;33m,[0m[0mlabel[0m[1;33m=[0m[1;34m'$V_{POI}$'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 4[1;33m [0maxes[0m[1;33m[[0m[1;36m1[0m[1;33m][0m[1;33m.[0m[0mplot[0m[1;33m([0m[0mpr[0m[1;33m.[0m[0mT[0m[1;33m,[0m[0mpr[0m[1;33m.[0m[0mget_values[0m[1;33m([0m[1;34m'Q_PMV'[0m[1;33m)[0m[1;33m/[0m[1;36m1e6[0m[1;33m,[0m[0mlabel[0m[1;33m=[0m[1;34m'$Q_{PMV}$'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [0maxes[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m.[0m[0mset_ylabel[0m[1;33m([0m[1;34m'Voltage (p.u.)'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [0maxes[0m[1;33m[[0m[1;36m1[0m[1;33m][0m[1;33m.[0m[0mset_ylabel[0m[1;33m([0m[1;34m'Reactive Power (Mvar)'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\workenv\lib\site-packages\pydae\systems\ier\proyecto.py[0m in [0;36mget_values[1;34m(self, name)[0m
[0;32m    549[0m             [0mvalues[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mZ[0m[1;33m[[0m[1;33m:[0m[1;33m,[0m[0mself[0m[1;33m.[0m[0moutputs_list[0m[1;33m.[0m[0mindex[0m[1;33m([0m[0mname[0m[1;33m)[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m    550[0m [1;33m[0m[0m
[1;32m--> 551[1;33m         [1;32mreturn[0m [0mvalues[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    552[0m [1;33m[0m[0m
[0;32m    553[0m     [1;32mdef[0m [0mget_mvalue[0m[1;33m([0m[0mself[0m[1;33m,[0m[0mnames[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mUnboundLocalError[0m: local variable 'values' referenced before assignment
UnboundLocalError: local variable 'values' referenced before assignment

